### ISSUE TITLE
Waiting for instructions to use the algorithm with natural images

### ISSUE THREAD

**Issue by areiasfi** [UNC-optics/DeepCGH#1]
Hi,

Great project, thank you! I am waiting for the instructions to use the network with natural images. I would like to use it for our 2p microscope to activate cell in the zebrafish brain.

Best wishes,
Edite

**Comment by hosseybposh** [comment]
hello and thank you for your kind words.
If your goal is to target neurons, you need to create a dataset of random disks and train the model with that dataset (see the examples in the tutorial). Each disk represents a neuron that needs to be targeted. For optogenetics applications I'd strongly recommend such a model since we achieve very high quality results.
For natural images, the results that are shown in the manuscript correspond to a model that is trained on images of lines and tested on natural images. We're working on models that are trained on natural images and will update our software package as soon as we can.

**Comment by areiasfi** [comment]
Oh, I see. Then I will try with disks. To apply this to the brain, I would generate a z stack of images with disks where the neurons I want to stimulate are, correct?
Thank you very much for your help!

**Comment by hosseybposh** [comment]
yes that's correct. You're very welcome.
For the training of the CNN you can use our data generator which randomly located disks. But for testing, you'll need to know exactly where your neurons are, generate the associated image, and use the `get_hologram` method to get the SLM phase. You can specify the size of the hologram and the number of depth planes with the `shape` parameter.
You'll also need to optically align your hologram synthesis hardware with your microscope but that's a different topic.
